import SwiftUI
import AkitoStationCore
struct AkitoStationSettings:View {
 @EnvironmentObject var store:LibraryStore;@Environment(\.dismiss) var dismiss;@State var category="Storage Locations";@State var system:Platform = .nes;@AppStorage("disableArtworkDownloads") var disableArtwork=false
 @State private var resetAll=false
 @State private var resetLocations=false
 @State private var resetGeneration=UUID()
 let baseCategories=["General","Emulators","Emulator Settings","Graphics","Audio","Controllers","BIOS / Firmware / Keys","Packages / Licenses","Systems","Storage Locations","AI Assistant","Emulator Updates","Advanced"]
 var categories:[String]{baseCategories.filter{BuildEdition.isDeveloper || !["AI Assistant","Advanced"].contains($0)} + ["Appearance"] + (BuildEdition.isDeveloper ? [] : ["Akito Station PRO"])}
 var body:some View{NavigationSplitView{List(categories,id:\.self,selection:$category){Text($0)}.scrollContentBackground(.hidden).background(IceTheme.navy).navigationTitle("Settings").frame(minWidth:170)}detail:{VStack(alignment:.leading){HStack{Text(category).font(.title2.bold());Spacer();Button("Reset All Settings…"){resetAll=true}.disabled(!store.canResetSettings);Button("Done"){dismiss()}}.padding(.bottom,16);ScrollView{content.id(resetGeneration).frame(maxWidth:.infinity,alignment:.leading)}}.padding(24).background(IceBackdrop())}.preferredColorScheme(.dark).tint(IceTheme.cyan).alert("Reset all settings?",isPresented:$resetAll){Button("Cancel",role:.cancel){};Button("Reset All Settings",role:.destructive){store.resetAllSettings();resetGeneration=UUID()}}message:{Text("Restore storage locations, system and game profiles, controller mappings, managed emulator settings, artwork and update preferences. Custom library paths and update sources are cleared. Configuration files are backed up. ROMs, saves, firmware and runtimes remain at their existing locations; add your libraries again afterward. Stop any independently launched emulators first.")}.alert("Reset storage locations?",isPresented:$resetLocations){Button("Cancel",role:.cancel){};Button("Reset Locations",role:.destructive){store.resetStorage(all:true);resetGeneration=UUID()}}message:{Text("Use the default Data folder, clear location overrides and remove library paths. Files are not moved or deleted. Add your ROM libraries again afterward.")}}
 @ViewBuilder var content:some View{switch category{
 case "Storage Locations":storageView
 case "Systems":VStack(alignment:.leading,spacing:20){Picker("Console",selection:$system){ForEach(Platform.allCases){Text($0.title).tag($0)}};if let name=ExternalEmulator.name(system){Text("Games open in "+name+". Configure graphics, controllers, firmware and saves in that emulator.");Button("Open "+name){store.openExternal(system)}}else if store.engine(system) != nil{ProfileEditor(profile:Binding(get:{store.systemProfiles[system.rawValue] ?? GameProfile()},set:{store.saveSystem($0,system)}),nativeGPU:GraphicsConfiguration.scalableEngines.contains(store.engine(system) ?? ""),engine:store.engine(system) ?? "");Text(EmbeddedRuntime.unavailableReason(engine:store.engine(system) ?? "") ?? (ManagedLaunch.engines.contains(store.engine(system) ?? "") ? "This runtime currently uses its own game window. Embedded video and controller integration are not yet available.":"GPU presentation is enabled. CPU emulation still runs on the CPU.")).font(.caption).foregroundStyle(.secondary)}else{Text("Requires Emulator").font(.headline);Text(requirement(system));Text("Install, import or relink a compatible emulator in Emulators. Desktop runtimes open their own game window.").foregroundStyle(.secondary)}}
 case "Emulators":VStack(alignment:.leading,spacing:16){Picker("Console",selection:$system){ForEach(Platform.allCases.filter{$0 != .unknown}){Text($0.title).tag($0)}};OptionalRuntimePanel(platform:system)}
 case "Emulator Settings":VStack(alignment:.leading,spacing:16){Picker("Console",selection:$system){ForEach(Platform.allCases.filter{$0 != .unknown}){Text($0.title).tag($0)}};EmulatorSettingsPanel(system:system).id(system.rawValue+"-"+(store.engine(system) ?? ""))}
 case "Emulator Updates":runtimeView
 case "Akito Station PRO":PublicPaymentSettings(premium: .shared)
 case "Appearance":PremiumSettings()
 case "Controllers":ControllerSettings()
 case "BIOS / Firmware / Keys":FirmwareSettings()
 case "Packages / Licenses":ContentInstallView()
 case "Graphics","Audio":VStack(alignment:.leading,spacing:16){Text("Defaults are configurable per console in Systems, with per-game overrides in game details.");Button("Open emulator settings"){category="Emulator Settings"};Button("Open simplified presets"){category="Systems"};Text(category=="Graphics" ? "Open Emulator Settings for the complete configuration present in each managed emulator and the options reported by each embedded core.":"Core sample rate is routed to CoreAudio through AVAudioEngine. Volume is persisted per system and game.").foregroundStyle(.secondary)}
 default:VStack(alignment:.leading,spacing:16){Text("Akito Station").font(.largeTitle.bold());Text("Native Apple Silicon · Akito Station-managed emulation");Toggle("Use local artwork only",isOn:$disableArtwork);Text("Artwork lookup sends the visible game title and console to the public Libretro thumbnail repository. Downloads are cached in Metadata; ROM contents are never sent.").font(.caption).foregroundStyle(.secondary);Text("Double-click a game to play. Use ⌘P to pause, ⌘S to save state, and ⌘L to load state during play.");Text("Individual game URLs use akito://<game-id> and share the same runtime installation.").foregroundStyle(.secondary)}
 }}
 var storageView:some View{VStack(alignment:.leading,spacing:18){Button("Reset Storage Locations…"){resetLocations=true}.disabled(!store.canResetSettings);Text("Resets change paths only. Existing files stay where they are.").font(.caption).foregroundStyle(.secondary);location("Master Akito Station data root",store.storage?.root.path ?? "Not configured"){store.setLocation(nil)};Button("Reset master root to default"){store.resetStorage()}.disabled(!store.canResetSettings);Button("Move managed data with verification…"){store.migrateRoot()}.disabled(store.busy);Text("Migration retains the original copy after verification. Individual overrides stay in place.").font(.caption).foregroundStyle(.secondary);Divider();HStack{Text("ROM Libraries").font(.headline);Spacer();Button("Add folder…"){store.addLibrary()}};ForEach(store.storage?.libraries ?? [],id:\.path){l in HStack{Text(l.path).font(.caption).textSelection(.enabled);Spacer();Button("Remove"){store.storage?.libraries.removeAll{$0.path==l.path};store.attempt{try store.savePreferences()}}}};Button("Scan libraries"){store.scan()}.disabled(store.busy);Divider();ForEach(StorageKind.allCases){kind in VStack(alignment:.trailing){location(kind.title,store.storage?.overrides[kind.rawValue]?.path ?? "Master root / \(kind.rawValue)"){store.setLocation(kind)};Button("Reset to master root"){store.resetStorage(kind)}.disabled(!store.canResetSettings || store.storage?.overrides[kind.rawValue]==nil);if kind != .firmware{Button("Move managed data…"){store.migrateLocation(kind)}.font(.caption).disabled(store.busy)}}}}}
 func location(_ title:String,_ path:String,_ action:@escaping()->Void)->some View{HStack{VStack(alignment:.leading,spacing:4){Text(title).font(.headline);Text(path).font(.caption).foregroundStyle(.secondary).textSelection(.enabled)};Spacer();Button("Choose…",action:action)}}
 var runtimeView:some View{RuntimeUpdatesView()}
 func requirement(_ p:Platform)->String{switch p{case .gc,.wii:return "Dolphin native ARM64 core requires a managed non-frontend build and Metal/MoltenVK integration.";case .ps2:return "ARMSX2 is the native ARM64 candidate. Its backend needs integration and user-supplied PS2 BIOS validation.";case .ps1:return "DuckStation requires managed backend integration and user-supplied BIOS routing.";case .psp:return "PPSSPP requires managed native backend and graphics integration.";case .n64:return "Mupen64Plus-Next requires an OpenGL hardware context; this host currently supports software video cores.";case .nds,.n3ds:return "A maintained DS/3DS engine needs touchscreen, firmware and graphics integration.";default:return "This platform requires an independently validated native runtime adapter and any required user-supplied system resources."}}
}
struct ProfileEditor:View {
 @Binding var profile:GameProfile
 var nativeGPU=false
 var engine=""
 var body:some View{VStack(alignment:.leading,spacing:15){Button("Reset profile to defaults"){profile=GameProfile()};if EmulatorSettings.native(profile){Text("Native emulator settings are enabled. Edit graphics and controller options in Emulator Settings.").foregroundStyle(.secondary)};if engine == "cemu"{Toggle("Use native Cemu audio routing",isOn:Binding(get:{profile.options["arm.cemu.audio.native"] == "true"},set:{profile.options["arm.cemu.audio.native"]=String($0)}));Text("By default, TV and GamePad sound use the current macOS output and the volume below. Enable native audio routing to use the devices and volumes in Emulator Settings.").font(.caption).foregroundStyle(.secondary)};if engine == "cemu" && !EmulatorSettings.native(profile){cemuGraphics};Text(EmulatorSettings.native(profile) ? "Native emulator configuration" : engine == "cemu" ? "Display and audio" : nativeGPU ? (engine == "dolphin" || engine == "armsx2" || engine == "pcsx2" ? "Metal GPU rendering":"Vulkan GPU rendering"):"Metal presentation · native resolution").font(.headline);if nativeGPU && !EmulatorSettings.native(profile){HStack{Text("Graphics preset");ForEach(["Performance","Balanced","Quality"],id:\.self){name in Button(name){GraphicsConfiguration.applyPreset(name,to:&profile)}}};Text("Performance uses 1× resolution; Balanced 2×; Quality 3×. All keep VSync enabled. Higher resolution increases GPU work.").font(.caption).foregroundStyle(.secondary);Stepper("Resolution: \(profile.resolutionScale)×",value:$profile.resolutionScale,in:1...8);Toggle("VSync",isOn:$profile.vsync);if engine != "dolphin"{Picker("Anisotropic filtering",selection:Binding(get:{GraphicsConfiguration.anisotropy(profile)},set:{profile.options["arm.graphics.anisotropy"]=String($0)})){ForEach([1,2,4,8,16],id:\.self){Text("\($0)×").tag($0)}}};Text("GPU rendering is the default. Console CPU instructions cannot be moved to the GPU with a graphics setting.").font(.caption).foregroundStyle(.secondary)};Picker("Aspect",selection:$profile.aspect){Text("Original").tag("Original");Text("Stretch").tag("Stretch")};Toggle("Fullscreen",isOn:$profile.fullscreen);Picker("Input",selection:$profile.controller){Text("Automatic").tag("Automatic");Text("Keyboard").tag("Keyboard")};HStack{Text("Volume");Slider(value:$profile.volume,in:0...1);Text("\(Int(profile.volume*100))%").monospacedDigit()}}}
 var cemuGraphics:some View{VStack(alignment:.leading,spacing:12){
 Text("Wii U · Vulkan GPU rendering").font(.headline)
 HStack{Text("Scaling preset");Button("Performance"){profile.options["arm.cemu.filter"]="0";profile.vsync=true};Button("Balanced"){profile.options["arm.cemu.filter"]="1";profile.vsync=true};Button("Quality"){profile.options["arm.cemu.filter"]="2";profile.vsync=true}}
 Picker("Upscale filter",selection:Binding(get:{profile.options["arm.cemu.filter"] ?? "1"},set:{profile.options["arm.cemu.filter"]=$0})){
 Text("Bilinear").tag("0");Text("Bicubic").tag("1");Text("Hermite").tag("2");Text("Nearest neighbor").tag("3")}
 Toggle("VSync",isOn:$profile.vsync)
 Toggle("Asynchronous shader compilation",isOn:Binding(get:{profile.options["arm.cemu.async"] != "false"},set:{profile.options["arm.cemu.async"]=String($0)}))
 Text("These presets change display scaling. Internal resolution uses Cemu’s game-specific graphics packs; existing pack selections are preserved.").font(.caption).foregroundStyle(.secondary)
 }}

}
